spring:
  application:
    name: product-service

server:
  port: 9000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    url: /openAPI.yaml


management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    env:
      enabled: true
    metrics:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
