spring:
  application:
    name: product-service
  devtools:
    add-properties: ${SPRING_DEVTOOLS_ADD_PROPERTIES:true}
  datasource:
    url: jdbc:mysql://localhost:3306/products
    username: root
    password: Logan123@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    url: /openAPI.yaml


management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    env:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  datadog:
    metrics:
      export:
        api-key: ${DATADOG_API_KEY}
        uri: https://us5.datadoghq.com
        step: 10s
        host-tag: ${spring.application.name}
  metrics:
    tags:
      application.name: ${spring.application.name}
      env: ${SPRING_PROFILES_ACTIVE:default}
#logging:
#  level:
#    root: debug

